# CONSTANTS

# COLUMN NAMES
DATE = 'date'
REPORT_DATE = 'REPORT_DATE'
SHIFTED_DATE = 'shifted_date'
TICKER = 'TICKER'
AQUIRED = 'AQUIRED/DISPOSED'
PRICE_PER_UNIT = 'PRICE_PER_UNIT'
AMOUNT = 'AMOUNT'
CLOSE = 'close'
HIGH = 'high'
LOW = 'low'
ADJUSTED_CLOSE = 'adjusted close'
ADJUSTED_HIGH = 'adjusted high'
ADJUSTED_LOW = 'adjusted low'
HOLDING_BEFORE = 'HOLDING_BEFORE'

IS_DIRECTOR = 'IS_DIRECTOR'
IS_OFFICER = 'IS_OFFICER'
IS_MAJOR_OWNER = 'IS_10%_OWNER'
IS_OTHER = 'OTHER'