# CONSTANTS

PRICE_PER_UNIT = 'PRICE_PER_UNIT'
AMOUNT = 'AMOUNT'
ADJUSTED_CLOSE = 'adjusted close'
HOLDING_BEFORE = 'HOLDING_BEFORE'

IS_DIRECTOR = 'IS_DIRECTOR'
IS_OFFICER = 'IS_OFFICER'
IS_MAJOR_OWNER = 'IS_10%_OWNER'
IS_OTHER = 'OTHER'